services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./src:/home/node/app/src
      - ./public:/home/node/app/public
      - ./vite.config.js:/home/node/app/vite.config.js
      - ./index.html:/home/node/app/index.html
      - ./dist:/home/node/app/dist
    ports:
      - 3000:80
    command: npm run dev